jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.5

language: node_js
node_js:
  - 12
  - 14

install:
  - yarn --frozen-lockfile

script:
  - yarn build
  - yarn test
